#!/usr/bin/env bash

# Check updated version
if git --no-pager diff --exit-code package.json; then
  echo 'No version update'
  exit 1
fi

version=$(node -e "console.log(require('./package.json').version)")
echo $version

for file in packages/*; do
  echo "updating $file"
  sed -i "" -e "s/\"version\": \"[0-9.]*\"/\"version\": \"${version}\"/" $file/package.json
done

git commit . -m "bump version $version"
git tag $version
git push

for file in packages/*; do
  cd $file
  npm publish
  cd ../..
done
