import {
  Blockquote,
  BoldBlock,
  BulltList,
  Center,
  CodeBlock,
  ColorBlock,
  Div,
  Doc,
  Heading,
  HardBreak,
  Hr,
  Image,
  ItalicBlock,
  LinkBlock,
  ListItem,
  Paragraph,
  Quote,
  Right,
  ShikiBlock,
  ShikiInline,
  SizeBlock,
  Smiley,
  Video,
  SpoilerBlock,
  Text
} from '../nodes';

import {
  BoldInline,
  CodeInline,
  ColorInline,
  ItalicInline,
  LinkInline,
  SizeInline,
  Span,
  SpoilerInline,
  Strike,
  Underline
} from '../marks';

export default function(editor) {
  return [
    new Doc(),
    new Text(),
    new Paragraph(),
    new Heading(),
    new SpoilerInline(), // must be above other marks in order to obtain greater priorirty
    new LinkInline(),
    new Span(),
    new BoldInline(),
    new ItalicInline(),
    new ColorInline(),
    new SizeInline(),
    new Underline(),
    new Strike(),
    new CodeInline(),
    new Center(),
    new Right(),
    new LinkBlock(),
    new ShikiInline(),
    new BoldBlock(),
    new ItalicBlock(),
    new SizeBlock(),
    new ColorBlock(),
    new ShikiBlock(),
    new Blockquote(),
    new BulltList(),
    new CodeBlock(),
    new Div(),
    new HardBreak(),
    new Hr(),
    new Smiley({ origin: editor.options.shikiRequest.origin }),
    new Image(),
    new Video(),
    new ListItem(),
    new Quote({ origin: editor.options.shikiRequest.origin }),
    new SpoilerBlock()
  ];
}
